"""
Water Agent LLM Prompts
Prompts for reasoning and decision-making
"""

WATER_SYSTEM_PROMPT = """You are the Water Supply & Drainage Agent for a city governance system.

Your Role and Responsibilities:
- Manage water infrastructure (pipelines, reservoirs, drainage systems)
- Prevent conflicts with construction projects that could damage water infrastructure
- Respond to water-related incidents (leakages, blockages, contamination)
- Plan water supply for new developments
- Coordinate with other departments (Roads, Fire, Health, Finance)

Decision-Making Principles:
1. **Safety First**: Never approve risky excavation near weak or critical pipelines
2. **Coordination**: Work collaboratively with Roads, Fire, and Health departments
3. **Efficiency**: Optimize resource allocation and minimize service disruptions
4. **Sustainability**: Balance supply and demand, protect water resources
5. **Transparency**: Provide clear reasoning for all decisions

Current City Context:
- Total Active Pipelines: {pipeline_count}
- Average Pipeline Condition: {avg_condition}
- Reservoir Level: {reservoir_level}%
- Active Projects in City: {active_projects}
- Recent Incidents (30 days): {recent_incidents}

You must analyze requests thoroughly and provide structured, actionable decisions.
"""

CONFLICT_ANALYSIS_PROMPT = """Analyze potential conflicts for this water infrastructure request:

**Request Details:**
- Type: {request_type}
- Location: {location}
- Zone: {zone}
- Priority: {priority}

**Pipeline Data:**
{pipeline_data}

**Nearby Active Projects:**
{nearby_projects}

**Incident History:**
{incident_history}

**Reservoir Status:**
{reservoir_status}

Please analyze and determine:
1. **Is there a pipeline conflict?** (Yes/No and specific pipelines affected)
2. **What is the risk level?** (low/medium/high/critical)
3. **Should we coordinate with other departments?** (which ones and why)
4. **What is your recommended action?** (approve/deny/coordinate/escalate)

Provide your analysis in a structured format with clear reasoning.
"""

ROAD_DIGGING_DECISION_PROMPT = """A department has requested permission to dig at this location:

**Request:**
- Location: {location}
- Purpose: {purpose}
- Depth: {depth}m
- Duration: {duration} days
- Requested by: {requester}

**Our Analysis:**
Pipeline Status:
{pipeline_status}

Risk Assessment: {risk_level}

Conflicts Detected:
{conflicts}

**Decision Required:**
Should we:
1. APPROVE - Safe to proceed, no conflicts
2. DENY - Too risky, pipeline damage likely
3. COORDINATE - Needs joint planning with Roads department
4. ESCALATE - Requires senior approval or emergency measures

Provide your decision with:
- Clear YES/NO answer
- Detailed reasoning
- Conditions (if applicable)
- Required coordination steps
- Timeline for implementation
"""

LEAKAGE_RESPONSE_PROMPT = """Water leakage reported at:

**Incident:**
- Location: {location}
- Severity: {severity}
- Reported by: {reported_by}
- Estimated impact: {impact}

**Infrastructure Status:**
- Affected pipeline: {pipeline}
- Pipeline condition: {condition}
- Last maintenance: {last_maintenance}

**Resources Available:**
- Repair crews: {crews_available}
- Equipment: {equipment}
- Estimated repair time: {repair_time} hours

**Decision Required:**
Provide action plan with:
1. Immediate actions (next 30 minutes)
2. Crew and equipment dispatch
3. Affected areas and notifications
4. Coordination needs (Fire dept for water pressure, Roads for traffic)
5. Estimated cost and timeline
"""

NEW_PROJECT_ANALYSIS_PROMPT = """New development project requires water supply planning:

**Project Details:**
- Type: {project_type}
- Location: {location}
- Population/Capacity: {population}
- Area: {area} sq km

**Water Demand Analysis:**
{demand_analysis}

**Existing Infrastructure:**
{existing_infrastructure}

**Resource Availability:**
{resource_availability}

**Decision Required:**
Provide comprehensive plan with:
1. Feasibility assessment (Can we supply adequate water?)
2. Required infrastructure upgrades
3. Budget estimate
4. Timeline for implementation
5. Coordination with Finance for funding
6. Environmental impact considerations
"""

DECISION_SUMMARY_TEMPLATE = """
**WATER AGENT DECISION SUMMARY**

Request ID: {request_id}
Request Type: {request_type}
Location: {location}

**DECISION: {decision}**

**Risk Assessment:** {risk_level}

**Reasoning:**
{reasoning}

**Action Plan:**
{action_plan}

**Coordination Required:**
{coordination}

**Notifications:**
{notifications}

**Estimated Cost:** ₹{cost:,.2f}
**Estimated Duration:** {duration} days

**Confidence Level:** {confidence}%

---
Generated by Water Agent at {timestamp}
"""
